#get testprograms impossible untill git works 
--- 
- name: Get and compile testprograms
  hosts: sfs
  tasks:
    - name: Get repo
      git:
        repo: "git@github.com:SoftwareForScience/power-monitoring.git"
        dest: powermonitoring
        recursive: yes

    - name: make FFT_with_MPI
      command: make 
      args:
          chdir: powermonitoring/2020-team/Test_programs/FFT_with_MPI 
    
    - name: make FFT_with_multithreading
      command: make 
      args:
          chdir: powermonitoring/2020-team/Test_programs/FFT_with_multithreading
    
    - name: make Mandelbrot_with_MPI
      command: make 
      args:
          chdir: powermonitoring/2020-team/Test_programs/Mandelbrot_with_MPI




