# IMPORTANT!!! the pi's must have access to the internet 
#              to be able to install dependencies 
# install this on all the pi's except the data collection pi 
---
- name: Install client
  hosts: sfs
  tasks:
    - name: Get aptitude
      become: true
      apt:
        name: aptitude
        force_apt_get: yes
    - name: Get packages
      become: true
      apt:
        pkg:
        - git
        - cmake
        - autoconf
        - automake
        state: latest

    - name: Get repo
      git:
        repo: "git@github.com:SoftwareForScience/power-monitoring.git"
        dest: powermonitoring
        recursive: yes

    - name: Run cmake in submodule (Libsocket++)
      command: cmake .
      args:
        chdir: powermonitoring/2020-team/client/lib/libsocket/

    - name: Build submodule (Libsocket++)
      become: true
      make:
        chdir: powermonitoring/2020-team/client/lib/libsocket
        target: install

    - name: Compile client
      command: g++ -std=c++11 -lsocket++ -o echoclient echo_client_conn.cpp
      args:
        chdir: powermonitoring/2020-team/client/src/
