# IMPORTANT!!! the pi's must have access to the internet 
#              to be able to install dependencies 
# install this on all the pi's except the data collection pi 
---
- name: Install client
  hosts: sfs
  tasks:
    - name: Get repo
      git:
        repo: "https://gitlab.fdmci.hva.nl/sfs-power-monitoring/powermonitoring.git"
        dest: lib
        recursive: yes

