---
- name: start up powermonitoring
  shell: nohup python3 /home/pi/Documents/sfs/CurrentMeasurement/metric_INA219.py </dev/null >/dev/null 2>&1 &

- name: start prometheus
  shell: nohup /home/pi/Documents/sfs/prometheus-2.7.0.linux-armv7/prometheus --config.file=/home/pi/Documents/sfs/prometheus-2.7.0.linux-armv7/prometheus.yml </dev/null >/dev/null 2>&1 &
