# Module: prometheus
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/6.x/metricbeat-module-prometheus.html

- module: prometheus
  #metricsets:
  #  - stats
  period: 10s
  hosts: ["127.0.0.1:9090"]
  #metrics_path: /metrics
  metrics_path: '/federate'
  query:
    'match[]': '{__name__!=""}'
  namespace: example
  #username: "user"
  #password: "secret"

  # This can be used for service account based authorization:
  #  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  #ssl.certificate_authorities:
  #  - /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt

