---
- name: remove old Power Monitoring directory
  command: rm -r /home/pi/Documents/sfs
  ignore_errors: true

- name: update package list
  command: apt-get update
  ignore_errors: true

- name: clone git repo
  command: git clone https://github.com/Astron-Power-Monitoring/RPI.git /home/pi/Documents/sfs
  
- name: install pip3
  command: apt install python3-pip

- name: pip3 install monasca-agent
  command: pip3 install monasca-agent

- name: pip3 install INA219 python module
  command: pip3 install pi-ina219


  

