# Module: prometheus
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/6.x/metricbeat-module-prometheus.html

- module: prometheus
  #metricsets:
  #  - stats
  period: 10s
  hosts: ["172.18.0.3:9090"]
  metrics_path: /metrics
  namespace: prom1
  #username: "user"
  #password: "secret"

  # This can be used for service account based authorization:
  #  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  #ssl.certificate_authorities:
  #  - /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt

