 image: docker:stable

 variables:
   # For non-Kubernetes executors, we use tcp://docker:2375/
   DOCKER_HOST: tcp://docker:2375/
   # When using dind, it's wise to use the overlayfs driver for
   # improved performance.
   DOCKER_DRIVER: overlay2

 services:
   - docker:dind

 before_script:
   - docker info

 build:
   stage: build
   script:
     - docker build -t registry.twizzel.net/hva/sfs-power-monitoring/prometheus-powermeter-build .
     - docker ps
