
--- 
- name: Install FFT dependencies (this might take a while)
  hosts: sfs
  tasks:
    - name: Get aptitude
      become: true
      apt:
        name: aptitude
        force_apt_get: yes

    - name: Get openMPI packages
      become: true
      apt:
        pkg:
        - openmpi-bin
        - openmpi-common
        - libopenmpi3
        - libopenmpi-dev
        state: latest

############################ fftw intallation 

    - name: Create target directory
      file: path=FFT/src state=directory 

    - name: get fftw-3.3.8.tar.gz
      copy:
        src: src/fftw-3.3.8.tar.gz
        dest: FFT/src
       
    - name: Unarchive fftw-3.3.8
      command: tar -C FFT/src -xvf FFT/src/fftw-3.3.8.tar.gz
      become: true

    - name: configure fftw
      command: ./configure --enable-mpi --enable-threads
      args:
          chdir: FFT/src/fftw-3.3.8 
      become: true

    - name: make fftw (this might take a while)
      command: make -j 3
      args:
          chdir: FFT/src/fftw-3.3.8 
      become: true

    - name: make install fftw
      command: make install
      args:
          chdir: FFT/src/fftw-3.3.8 
      become: true

