# IMPORTANT!!! the pi's must have access to the internet 
#              to be able to install dependencies 
# install this on all the pi's except the data collection pi 
---
- name: Install client
  hosts: sfs
  tasks:
    - name: Get aptitude
      become: true
      apt:
        name: aptitude
        force_apt_get: yes
    - name: Get packages
      become: true
      apt:
        pkg:
        - git
        - cmake
        - autoconf
        - automake
        state: latest
    - name: pre-create folder
      command: mkdir -p powermonitoring/client/src/

    - name: Get repo
      git:
        repo: "https://github.com/dermesser/libsocket.git"
        dest: powermonitoring/client/lib/libsocket
        recursive: yes
    - name: Run cmake in submodule (Libsocket++)
      command: cmake .
      args:
        chdir: powermonitoring/client/lib/libsocket/

    - name: Build submodule (Libsocket++)
      become: true
      make:
        chdir: powermonitoring/client/lib/libsocket
        target: install

    - name: Copy src file
      copy:
        src: /Users/stefanschokker/Downloads/echo_client_conn.cpp
        dest: powermonitoring/client/src/echo_client_conn.cpp

    - name: Compile client
      command: g++ -std=c++11 -lsocket++ -o echoclient echo_client_conn.cpp
      args:
        chdir: powermonitoring/client/src/
